spring:
  application:
    name: eurekasub9902
server:
  port: 9902
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9901/eureka/,http://localhost:9903/eureka/
  register-with-eureka: false

