spring:
  application:
    name: eurekamaster
server:
  port: 9901
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9902/eureka/,http://localhost:9903/eureka/
    register-with-eureka: false
    fetchRegistry: false