spring:
  application:
    name: eurekasub9903
server:
  port: 9903
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9901/eureka/,http://localhost:9902/eureka/
  register-with-eureka: false




